-- Disable Row Level Security on all tables
-- This will resolve the Supabase linter warnings

ALTER TABLE "Projection" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Status" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SignedFee" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AsrFee" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ClosedProject" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectAssignment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectManager" DISABLE ROW LEVEL SECURITY;
